"""init migration

Revision ID: 12f124975d65
Revises: 49b1a4c0e69e
Create Date: 2016-03-03 23:15:39.228000

"""

# revision identifiers, used by Alembic.
revision = '12f124975d65'
down_revision = '49b1a4c0e69e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkMsgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkMsgs_timestamp'), 'checkMsgs', ['timestamp'], unique=False)
    op.add_column(u'activitys', sa.Column('sponsor', sa.String(length=125), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'activitys', 'sponsor')
    op.drop_index(op.f('ix_checkMsgs_timestamp'), table_name='checkMsgs')
    op.drop_table('checkMsgs')
    ### end Alembic commands ###
