"""init migration

Revision ID: 1839a54fd331
Revises: None
Create Date: 2016-01-30 23:18:14.503000

"""

# revision identifiers, used by Alembic.
revision = '1839a54fd331'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('authorid', sa.Integer(), nullable=True),
    sa.Column('activityid', sa.Integer(), nullable=True),
    sa.Column('commentid', sa.Integer(), nullable=True),
    sa.Column('likenumber', sa.Integer(), nullable=True),
    sa.Column('commentnumber', sa.Integer(), nullable=True),
    sa.Column('disable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['activityid'], ['activitys.id'], ),
    sa.ForeignKeyConstraint(['authorid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commentacts_timestamp'), 'commentacts', ['timestamp'], unique=False)
    op.create_table('commentactimageattachs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('imageid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commentid'], ['commentacts.id'], ),
    sa.ForeignKeyConstraint(['imageid'], ['imageurls.id'], ),
    sa.PrimaryKeyConstraint('id', 'commentid', 'imageid')
    )
    op.create_table('likecommentacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commentid'], ['commentacts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'userid', 'commentid')
    )
    op.add_column(u'schoolcertifications', sa.Column('checkresult', sa.Boolean(), nullable=True))
    op.drop_column(u'schoolcertifications', 'picture_number')
    op.add_column(u'users', sa.Column('certification', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'certification')
    op.add_column(u'schoolcertifications', sa.Column('picture_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column(u'schoolcertifications', 'checkresult')
    op.drop_table('likecommentacts')
    op.drop_table('commentactimageattachs')
    op.drop_index(op.f('ix_commentacts_timestamp'), table_name='commentacts')
    op.drop_table('commentacts')
    ### end Alembic commands ###
