"""init migration

Revision ID: 1f02f7d86155
Revises: 3210ed98a7a0
Create Date: 2016-01-30 21:51:13.042000

"""

# revision identifiers, used by Alembic.
revision = '1f02f7d86155'
down_revision = '3210ed98a7a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schoolcertifications', sa.Column('checkresult', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schoolcertifications', 'checkresult')
    ### end Alembic commands ###
