"""init migration

Revision ID: 253bfbe64e66
Revises: 521f7ae9159c
Create Date: 2016-02-26 16:15:45.648000

"""

# revision identifiers, used by Alembic.
revision = '253bfbe64e66'
down_revision = '521f7ae9159c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('androidversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('v1', sa.Integer(), nullable=True),
    sa.Column('v2', sa.Integer(), nullable=True),
    sa.Column('v3', sa.Integer(), nullable=True),
    sa.Column('wemeurl', sa.String(length=256), nullable=True),
    sa.Column('disable', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_androidversions_timestamp'), 'androidversions', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_androidversions_timestamp'), table_name='androidversions')
    op.drop_table('androidversions')
    ### end Alembic commands ###
