"""init migration

Revision ID: 2c333341bcb8
Revises: None
Create Date: 2015-12-26 09:44:11.375000

"""

# revision identifiers, used by Alembic.
revision = '2c333341bcb8'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitytopofficials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageurl', sa.String(length=256), nullable=True),
    sa.Column('activityid', sa.Integer(), nullable=True),
    sa.Column('activitytitle', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activityimageattachs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityid', sa.Integer(), nullable=False),
    sa.Column('imageid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activityid'], ['activitys.id'], ),
    sa.ForeignKeyConstraint(['imageid'], ['imageurls.id'], ),
    sa.PrimaryKeyConstraint('id', 'activityid', 'imageid')
    )
    op.add_column(u'activitys', sa.Column('advertise', sa.String(length=32), nullable=True))
    op.add_column(u'activitys', sa.Column('authorid', sa.Integer(), nullable=True))
    op.add_column(u'activitys', sa.Column('detail', sa.Text(), nullable=True))
    op.add_column(u'activitys', sa.Column('label', sa.String(length=32), nullable=True))
    op.add_column(u'activitys', sa.Column('passflag', sa.Boolean(), nullable=True))
    op.add_column(u'activitys', sa.Column('remark', sa.String(length=32), nullable=True))
    op.add_column(u'activitys', sa.Column('signnumber', sa.Integer(), nullable=True))
    op.add_column(u'activitys', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column(u'activitys', sa.Column('whetherimage', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'activitys', 'users', ['authorid'], ['id'])
    op.add_column(u'users', sa.Column('lookcount', sa.Integer(), nullable=True))
    op.drop_column(u'users', 'yaoda')
    op.drop_column(u'users', 'autumn1')
    op.drop_column(u'users', 'autumn3')
    op.drop_column(u'users', 'autumn2')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('autumn2', mysql.VARCHAR(length=32), nullable=True))
    op.add_column(u'users', sa.Column('autumn3', mysql.VARCHAR(length=32), nullable=True))
    op.add_column(u'users', sa.Column('autumn1', mysql.VARCHAR(length=32), nullable=True))
    op.add_column(u'users', sa.Column('yaoda', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column(u'users', 'lookcount')
    op.drop_constraint(None, 'activitys', type_='foreignkey')
    op.drop_column(u'activitys', 'whetherimage')
    op.drop_column(u'activitys', 'timestamp')
    op.drop_column(u'activitys', 'signnumber')
    op.drop_column(u'activitys', 'remark')
    op.drop_column(u'activitys', 'passflag')
    op.drop_column(u'activitys', 'label')
    op.drop_column(u'activitys', 'detail')
    op.drop_column(u'activitys', 'authorid')
    op.drop_column(u'activitys', 'advertise')
    op.drop_table('activityimageattachs')
    op.drop_table('activitytopofficials')
    ### end Alembic commands ###
