"""init migration

Revision ID: 2cb5d3d6c16a
Revises: None
Create Date: 2016-01-30 16:41:11.776000

"""

# revision identifiers, used by Alembic.
revision = '2cb5d3d6c16a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schoolcertifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('school', sa.String(length=32), nullable=True),
    sa.Column('studentID', sa.String(length=64), nullable=True),
    sa.Column('pictureurl', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('checkflag', sa.Boolean(), nullable=True),
    sa.Column('checktime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schoolcertifications')
    ### end Alembic commands ###
