"""init migration

Revision ID: 2d6c153257ba
Revises: None
Create Date: 2015-12-27 09:18:14.718000

"""

# revision identifiers, used by Alembic.
revision = '2d6c153257ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guestid', sa.Integer(), nullable=True),
    sa.Column('hostid', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guestid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hostid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    ### end Alembic commands ###
