"""init migration

Revision ID: 2f0736e305a
Revises: 5534e80228dd
Create Date: 2016-01-22 22:54:52.962000

"""

# revision identifiers, used by Alembic.
revision = '2f0736e305a'
down_revision = '5534e80228dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatarvoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('avatarurl', sa.String(length=256), nullable=True),
    sa.Column('voiceurl', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatarvoices')
    ### end Alembic commands ###
