"""init migration

Revision ID: 3210ed98a7a0
Revises: 2cb5d3d6c16a
Create Date: 2016-01-30 21:34:09.746000

"""

# revision identifiers, used by Alembic.
revision = '3210ed98a7a0'
down_revision = '2cb5d3d6c16a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('certification', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'certification')
    ### end Alembic commands ###
