"""empty message

Revision ID: 3933bc34e6d0
Revises: None
Create Date: 2016-04-10 18:16:29.183909

"""

# revision identifiers, used by Alembic.
revision = '3933bc34e6d0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commentacts', 'readflag')
    op.add_column('comments', sa.Column('readflag', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'readflag')
    op.add_column('commentacts', sa.Column('readflag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
