"""init migration

Revision ID: 4381d18cbe5b
Revises: 52eaa48aa67e
Create Date: 2016-01-27 21:29:24.200000

"""

# revision identifiers, used by Alembic.
revision = '4381d18cbe5b'
down_revision = '52eaa48aa67e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatarvoices', sa.Column('cardflag', sa.Boolean(), nullable=True))
    op.add_column('avatarvoices', sa.Column('disable', sa.Boolean(), nullable=True))
    op.add_column('avatarvoices', sa.Column('gender', sa.String(length=32), nullable=True))
    op.add_column('avatarvoices', sa.Column('name', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatarvoices', 'name')
    op.drop_column('avatarvoices', 'gender')
    op.drop_column('avatarvoices', 'disable')
    op.drop_column('avatarvoices', 'cardflag')
    ### end Alembic commands ###
