"""init migration

Revision ID: 49b1a4c0e69e
Revises: 253bfbe64e66
Create Date: 2016-02-28 20:38:29.551000

"""

# revision identifiers, used by Alembic.
revision = '49b1a4c0e69e'
down_revision = '253bfbe64e66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('sponsor', sa.String(length=125), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitys', 'sponsor')
    ### end Alembic commands ###
