"""init migration

Revision ID: 4f61bef61c5a
Revises: None
Create Date: 2016-03-08 09:44:45.197000

"""

# revision identifiers, used by Alembic.
revision = '4f61bef61c5a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likefoodcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('foodcardid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['foodcardid'], ['foodcards.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'userid', 'foodcardid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likefoodcards')
    ### end Alembic commands ###
