"""init migration

Revision ID: 52eaa48aa67e
Revises: None
Create Date: 2016-01-25 19:50:59.722000

"""

# revision identifiers, used by Alembic.
revision = '52eaa48aa67e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatarvoices', sa.Column('avatar_number', sa.Integer(), nullable=True))
    op.add_column('avatarvoices', sa.Column('voice_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatarvoices', 'voice_number')
    op.drop_column('avatarvoices', 'avatar_number')
    ### end Alembic commands ###
