"""empty message

Revision ID: 84c647ff798e
Revises: None
Create Date: 2016-03-04 13:02:24.911034

"""

# revision identifiers, used by Alembic.
revision = '84c647ff798e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checkMsgs_phone', table_name='checkMsgs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_checkMsgs_phone', 'checkMsgs', ['phone'], unique=False)
    ### end Alembic commands ###
