"""empty message

Revision ID: e7b2c77ed722
Revises: None
Create Date: 2016-03-24 14:44:57.156140

"""

# revision identifiers, used by Alembic.
revision = 'e7b2c77ed722'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=128), nullable=True),
    sa.Column('disable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personalimages')
    ### end Alembic commands ###
