"""empty message

Revision ID: f19efb16897f
Revises: None
Create Date: 2016-02-01 21:53:54.876875

"""

# revision identifiers, used by Alembic.
revision = 'f19efb16897f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iosdevicetoken', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iosdevicetoken', 'timestamp')
    ### end Alembic commands ###
